// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoxydwfkcriwcrkukkjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpveHlkd2ZrY3Jpd2Nya3Vra2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTUyMDgsImV4cCI6MjA2NDk3MTIwOH0.1r5glmXBcpV60GcOjVvqfmKN74kAMfwJ67m7Os_IySE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);